# .pre-commit-config.yaml
# https://pre-commit.com/#new-hooks
# https://python-poetry.org/docs/pre-commit-hooks/

default_language_version:
  python: python3.12
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        language: python
        types: [python]
        args: ["--fix"]
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format
        language: python
        types: [python]
        args: []
