name: Build and Release EXE

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      # 3. Install dependencies using Poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # 4. Install PyInstaller
      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      # 5. Build the executable with PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name pid-sim src/gui/main.py

      # 6. Verify the build (optional)
      - name: Verify executable
        run: |
          if (!(Test-Path "dist\pid-sim.exe")) {
            Write-Error "Executable not found!"
            exit 1
          }

      # 7. Create Release and Upload EXE
      - name: Create Release and Upload EXE
        uses: ncipollo/release-action@v1
        with:
          tag: "v0.0.${{ github.run_number }}"
          name: "Release ${{ github.run_number }}"
          files: "dist/pid-sim.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
